#!/bin/bash

# Comprobar que se haya pasado el nombre del archivo como parámeto

if [ -z "$1" ]; then echo "Enviado: $1"
	exit 1
fi

# 1\. Asignar permisos de ejecución al archio

chmod u+x "$1"

# 2\. Agregar únicamente ese archio

git add "$1"

# 3\. Crear el commit utilizando el nombre del archivo
git commit -m "$1"

# 4\. Subir los cambios a GitHub
git push

# 5\. Usuario de Git 
echo "Tarea Enviada"


